/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package events_pkg


import(
	"time"
	"encoding/json"
	"github.com/apimatic/unirest-go"
	"pepipost_lib/apihelper_pkg"
	"pepipost_lib/configuration_pkg"
	"pepipost_lib/models_pkg"
)
/*
 * Client structure as interface implementation
 */
type EVENTS_IMPL struct {
     config configuration_pkg.CONFIGURATION
}

/**
 * Lets you to retrieve the email transaction logs.
 * @param    *time.Time                   startdate       parameter: Required
 * @param    models_pkg.EventsEnum        events          parameter: Optional
 * @param    models_pkg.SortEnum          sort            parameter: Optional
 * @param    *time.Time                   enddate         parameter: Optional
 * @param    *int64                       offset          parameter: Optional
 * @param    *int64                       limit           parameter: Optional
 * @param    *string                      subject         parameter: Optional
 * @param    *string                      xapiheader      parameter: Optional
 * @param    *string                      fromaddress     parameter: Optional
 * @param    *string                      email           parameter: Optional
 * @return	Returns the interface{} response from the API call
 */
func (me *EVENTS_IMPL) GetEventsGET (
            startdate *time.Time,
            events models_pkg.EventsEnum,
            sort models_pkg.SortEnum,
            enddate *time.Time,
            offset *int64,
            limit *int64,
            subject *string,
            xapiheader *string,
            fromaddress *string,
            email *string) (interface{}, error) {
    //the endpoint path uri
    _pathUrl := "/events"

    //variable to hold errors
    var err error = nil
    //the base uri for api requests
    _queryBuilder := configuration_pkg.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + _pathUrl

    //process optional query parameters
    _queryBuilder, err = apihelper_pkg.AppendUrlWithQueryParameters(_queryBuilder, map[string]interface{} {
        "startdate" : startdate,
        "events" : models_pkg.EventsEnumToValue(events),
        "sort" : models_pkg.SortEnumToValue(sort),
        "enddate" : enddate,
        "offset" : apihelper_pkg.ToString(*offset, "0"),
        "limit" : apihelper_pkg.ToString(*limit, "10"),
        "subject" : subject,
        "xapiheader" : xapiheader,
        "fromaddress" : fromaddress,
        "email" : email,
    })
    if err != nil {
        //error in query param handling
        return nil, err
    }

    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }
    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "api_key" : pepipost_lib.config.ApiKey,
    }

    //prepare API request
    _request := unirest.Get(_queryBuilder, headers)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request,false);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code == 400) {
        err = apihelper_pkg.NewAPIError("API Response", _response.Code, _response.RawBody)
    } else if (_response.Code == 401) {
        err = apihelper_pkg.NewAPIError("API Response", _response.Code, _response.RawBody)
    } else if (_response.Code == 403) {
        err = apihelper_pkg.NewAPIError("API Response", _response.Code, _response.RawBody)
    } else if (_response.Code == 405) {
        err = apihelper_pkg.NewAPIError("Invalid input", _response.Code, _response.RawBody)
    } else if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
            err = apihelper_pkg.NewAPIError("HTTP Response Not OK", _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal interface{}
    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil

}

