/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package events_pkg

import "time"
import "pepipost_lib/configuration_pkg"
import "pepipost_lib/models_pkg"

/*
 * Interface for the EVENTS_IMPL
 */
type EVENTS interface {
    GetEventsGET (*time.Time, models_pkg.EventsEnum, models_pkg.SortEnum, *time.Time, *int64, *int64, *string, *string, *string, *string) (interface{}, error)
}

/*
 * Factory for the EVENTS interaface returning EVENTS_IMPL
 */
func NewEVENTS(config configuration_pkg.CONFIGURATION) *EVENTS_IMPL {
    client := new(EVENTS_IMPL)
    client.config = config
    return client
}