/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg


/** The base Uri for API calls */
const BASEURI string = "https://api.pepipost.com/v5"



type CONFIGURATION_IMPL struct {
    /** Your Pepipost API Key. You will find the api key in the Pepipost application in Integrations. */
    /** Replace the value of ApiKey with an appropriate value */
    api_key string
}

/*
 * Getter function returning api_key
 */
func (me *CONFIGURATION_IMPL) ApiKey() string{
    return me.api_key
}

/*
 * Setter function setting up api_key
 */
func (me *CONFIGURATION_IMPL) SetApiKey(apiKey string) {
    me.api_key = apiKey
}

