/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg

import(
	"github.com/pepipost/pepipost-sdk-go/pepipost_lib/apihelper_pkg"
)
/* Setting up enums for Environments and Servers 
*/
type Environments int

type Servers int

// Environment Enums
const (
     PRODUCTION Environments = 1 + iota
)

// Servers Enums
const (
 	 SERVER1 Servers = 1 + iota
)

type CONFIGURATION_IMPL struct {
    /** Your Pepipost API Key. You will find the api key in the Pepipost application in Integrations. */
    /** Replace the value of ApiKey with an appropriate value */
    api_key string
}

/*
 * Getter function returning api_key
 */
func (me *CONFIGURATION_IMPL) ApiKey() string{
    return me.api_key
}

/*
 * Setter function setting up api_key
 */
func (me *CONFIGURATION_IMPL) SetApiKey(apiKey string) {
    me.api_key = apiKey
}

// Setting up Default Environment
var Environment = PRODUCTION

// A map of environments and their corresponding servers/baseurls
var EnvironmentsMap = map[Environments](map[Servers]string){

    PRODUCTION : map[Servers]string{
        SERVER1:"https://api.pepipost.com/v5/mail",
    },
}
 
// Make and return the map of parameters
func GetBaseURIParameters(config CONFIGURATION) map[string]interface{} {
     kvpMap := map[string]interface{}{
    }
    return kvpMap;
}

// Gets the URL for a particular alias in the current environment and appends it with template parameters
// return the baseurl
func GetBaseURI(server Servers, config CONFIGURATION) string {
    url := EnvironmentsMap[Environment][server]
    appendedURL, _ := apihelper_pkg.AppendUrlWithTemplateParameters(url, GetBaseURIParameters(config))
    return appendedURL

}
