/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package suppression_pkg

import "pepipost_lib/configuration_pkg"
import "pepipost_lib/models_pkg"

/*
 * Interface for the SUPPRESSION_IMPL
 */
type SUPPRESSION interface {
    Adddomainoremailtosuppressionlist (*models_pkg.AddemailordomaintoSuppressionlist) (interface{}, error)

    Removedomainoremailtosuppressionlist (*models_pkg.RemoveemailordomaintoSuppressionlist) (interface{}, error)
}

/*
 * Factory for the SUPPRESSION interaface returning SUPPRESSION_IMPL
 */
func NewSUPPRESSION(config configuration_pkg.CONFIGURATION) *SUPPRESSION_IMPL {
    client := new(SUPPRESSION_IMPL)
    client.config = config
    return client
}