/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package send_pkg

import "pepipost_lib/configuration_pkg"
import "pepipost_lib/models_pkg"

/*
 * Interface for the SEND_IMPL
 */
type SEND interface {
    CreateGenerateTheMailSendRequest (*models_pkg.Send) ([]string, error)
}

/*
 * Factory for the SEND interaface returning SEND_IMPL
 */
func NewSEND(config configuration_pkg.CONFIGURATION) *SEND_IMPL {
    client := new(SEND_IMPL)
    client.config = config
    return client
}