/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package subaccountsgetsubaccounts_pkg

import "pepipost_lib/configuration_pkg"

/*
 * Interface for the SUBACCOUNTSGETSUBACCOUNTS_IMPL
 */
type SUBACCOUNTSGETSUBACCOUNTS interface {
    GetSubaccountsGetSubAccountsGET (string) (interface{}, error)
}

/*
 * Factory for the SUBACCOUNTSGETSUBACCOUNTS interaface returning SUBACCOUNTSGETSUBACCOUNTS_IMPL
 */
func NewSUBACCOUNTSGETSUBACCOUNTS(config configuration_pkg.CONFIGURATION) *SUBACCOUNTSGETSUBACCOUNTS_IMPL {
    client := new(SUBACCOUNTSGETSUBACCOUNTS_IMPL)
    client.config = config
    return client
}