/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package subaccountsupdatesubaccount_pkg

import "pepipost_lib/configuration_pkg"
import "pepipost_lib/models_pkg"

/*
 * Interface for the SUBACCOUNTSUPDATESUBACCOUNT_IMPL
 */
type SUBACCOUNTSUPDATESUBACCOUNT interface {
    CreateSubaccountsUpdateSubaccountPOST (*models_pkg.Updatesubaccount) (interface{}, error)
}

/*
 * Factory for the SUBACCOUNTSUPDATESUBACCOUNT interaface returning SUBACCOUNTSUPDATESUBACCOUNT_IMPL
 */
func NewSUBACCOUNTSUPDATESUBACCOUNT(config configuration_pkg.CONFIGURATION) *SUBACCOUNTSUPDATESUBACCOUNT_IMPL {
    client := new(SUBACCOUNTSUPDATESUBACCOUNT_IMPL)
    client.config = config
    return client
}