/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package stats_pkg


import(
	"time"
	"encoding/json"
	"github.com/apimatic/unirest-go"
	"pepipost_lib/apihelper_pkg"
	"pepipost_lib/configuration_pkg"
	"pepipost_lib/models_pkg"
)
/*
 * Client structure as interface implementation
 */
type STATS_IMPL struct {
     config configuration_pkg.CONFIGURATION
}

/**
 * Lets you fetch all the subaccounts created by you
 * @param    *time.Time                         startdate         parameter: Required
 * @param    *time.Time                         enddate           parameter: Optional
 * @param    models_pkg.AggregatedByEnum        aggregatedBy      parameter: Optional
 * @param    *int64                             offset            parameter: Optional
 * @param    *int64                             limit             parameter: Optional
 * @return	Returns the interface{} response from the API call
 */
func (me *STATS_IMPL) GetStatsGET (
            startdate *time.Time,
            enddate *time.Time,
            aggregatedBy models_pkg.AggregatedByEnum,
            offset *int64,
            limit *int64) (interface{}, error) {
    //the endpoint path uri
    _pathUrl := "/stats"

    //variable to hold errors
    var err error = nil
    //the base uri for api requests
    _queryBuilder := configuration_pkg.BASEURI;

    //prepare query string for API call
   _queryBuilder = _queryBuilder + _pathUrl

    //process optional query parameters
    _queryBuilder, err = apihelper_pkg.AppendUrlWithQueryParameters(_queryBuilder, map[string]interface{} {
        "startdate" : startdate,
        "enddate" : enddate,
        "aggregated_by" : models_pkg.AggregatedByEnumToValue(aggregatedBy),
        "offset" : apihelper_pkg.ToString(*offset, "1"),
        "limit" : apihelper_pkg.ToString(*limit, "100"),
    })
    if err != nil {
        //error in query param handling
        return nil, err
    }

    //validate and preprocess url
    _queryBuilder, err = apihelper_pkg.CleanUrl(_queryBuilder)
    if err != nil {
        //error in url validation or cleaning
        return nil, err
    }
    //prepare headers for the outgoing request
    headers := map[string]interface{} {
        "user-agent" : "APIMATIC 2.0",
        "api_key" : pepipost_lib.config.ApiKey,
    }

    //prepare API request
    _request := unirest.Get(_queryBuilder, headers)
    //and invoke the API call request to fetch the response
    _response, err := unirest.AsString(_request,false);
    if err != nil {
        //error in API invocation
        return nil, err
    }

    //error handling using HTTP status codes
    if (_response.Code == 400) {
        err = apihelper_pkg.NewAPIError("API Response", _response.Code, _response.RawBody)
    } else if (_response.Code == 401) {
        err = apihelper_pkg.NewAPIError("API Response", _response.Code, _response.RawBody)
    } else if (_response.Code == 403) {
        err = apihelper_pkg.NewAPIError("API Response", _response.Code, _response.RawBody)
    } else if (_response.Code == 405) {
        err = apihelper_pkg.NewAPIError("Invalid input", _response.Code, _response.RawBody)
    } else if (_response.Code < 200) || (_response.Code > 206) { //[200,206] = HTTP OK
            err = apihelper_pkg.NewAPIError("HTTP Response Not OK", _response.Code, _response.RawBody)
    }
    if(err != nil) {
        //error detected in status code validation
        return nil, err
    }

    //returning the response
    var retVal interface{}
    if err != nil {
        //error in parsing
        return nil, err
    }
    return retVal, nil

}

