/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package subaccountsdelete_pkg

import "pepipost_lib/configuration_pkg"
import "pepipost_lib/models_pkg"

/*
 * Interface for the SUBACCOUNTSDELETE_IMPL
 */
type SUBACCOUNTSDELETE interface {
    DeleteSubaccountsDeleteDELETE (*models_pkg.DeleteSubacoount) (interface{}, error)
}

/*
 * Factory for the SUBACCOUNTSDELETE interaface returning SUBACCOUNTSDELETE_IMPL
 */
func NewSUBACCOUNTSDELETE(config configuration_pkg.CONFIGURATION) *SUBACCOUNTSDELETE_IMPL {
    client := new(SUBACCOUNTSDELETE_IMPL)
    client.config = config
    return client
}