/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package subaccountssetsubaccountcredit_pkg

import "pepipost_lib/configuration_pkg"
import "pepipost_lib/models_pkg"

/*
 * Interface for the SUBACCOUNTSSETSUBACCOUNTCREDIT_IMPL
 */
type SUBACCOUNTSSETSUBACCOUNTCREDIT interface {
    CreateSubaccountsSetsubaccountcreditPOST (*models_pkg.UpdateCredisofsubaccount) (interface{}, error)
}

/*
 * Factory for the SUBACCOUNTSSETSUBACCOUNTCREDIT interaface returning SUBACCOUNTSSETSUBACCOUNTCREDIT_IMPL
 */
func NewSUBACCOUNTSSETSUBACCOUNTCREDIT(config configuration_pkg.CONFIGURATION) *SUBACCOUNTSSETSUBACCOUNTCREDIT_IMPL {
    client := new(SUBACCOUNTSSETSUBACCOUNTCREDIT_IMPL)
    client.config = config
    return client
}