/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package PepipostClient

import(
	"pepipost_lib/configuration_pkg"
	"pepipost_lib/send_pkg"
)
/*
 * Client structure as interface implementation
 */
type PEPIPOST_IMPL struct {
     send send_pkg.SEND
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *PEPIPOST_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to Send controller
     * @return Returns the Send() instance
*/
func (me *PEPIPOST_IMPL) Send() send_pkg.SEND {
    if(me.send) == nil {
        me.send = send_pkg.NewSEND(me.config)
    }
    return me.send
}

