/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package PepipostClient

import(
	"github.com/pepipost/pepipost-sdk-go/pepipost_lib/configuration_pkg"
	"github.com/pepipost/pepipost-sdk-go/pepipost_lib/send_pkg"
)


/*
 * Interface for the PEPIPOST_IMPL
 */
type PEPIPOST interface {
    Send()                  send_pkg.SEND
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the PEPIPOST interface returning PEPIPOST_IMPL
 */
func NewPEPIPOST() PEPIPOST {
    pepipostClient := new(PEPIPOST_IMPL)
    pepipostClient.config = configuration_pkg.NewCONFIGURATION()

    return pepipostClient
}
