/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package subaccountsgetcreditddetails_pkg

import "pepipost_lib/configuration_pkg"

/*
 * Interface for the SUBACCOUNTSGETCREDITDDETAILS_IMPL
 */
type SUBACCOUNTSGETCREDITDDETAILS interface {
    GetcreditddetailsGET (string) (interface{}, error)
}

/*
 * Factory for the SUBACCOUNTSGETCREDITDDETAILS interaface returning SUBACCOUNTSGETCREDITDDETAILS_IMPL
 */
func NewSUBACCOUNTSGETCREDITDDETAILS(config configuration_pkg.CONFIGURATION) *SUBACCOUNTSGETCREDITDDETAILS_IMPL {
    client := new(SUBACCOUNTSGETCREDITDDETAILS_IMPL)
    client.config = config
    return client
}