/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package domaingetdomains_pkg

import "pepipost_lib/configuration_pkg"

/*
 * Interface for the DOMAINGETDOMAINS_IMPL
 */
type DOMAINGETDOMAINS interface {
    GetDomainStatusGET (*string, *string) (interface{}, error)
}

/*
 * Factory for the DOMAINGETDOMAINS interaface returning DOMAINGETDOMAINS_IMPL
 */
func NewDOMAINGETDOMAINS(config configuration_pkg.CONFIGURATION) *DOMAINGETDOMAINS_IMPL {
    client := new(DOMAINGETDOMAINS_IMPL)
    client.config = config
    return client
}