/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package subaccountscreatesubaccount_pkg

import "pepipost_lib/configuration_pkg"
import "pepipost_lib/models_pkg"

/*
 * Interface for the SUBACCOUNTSCREATESUBACCOUNT_IMPL
 */
type SUBACCOUNTSCREATESUBACCOUNT interface {
    CreateSubaccountsCreateSubaccountPOST (*models_pkg.CreateSubaccount) (interface{}, error)
}

/*
 * Factory for the SUBACCOUNTSCREATESUBACCOUNT interaface returning SUBACCOUNTSCREATESUBACCOUNT_IMPL
 */
func NewSUBACCOUNTSCREATESUBACCOUNT(config configuration_pkg.CONFIGURATION) *SUBACCOUNTSCREATESUBACCOUNT_IMPL {
    client := new(SUBACCOUNTSCREATESUBACCOUNT_IMPL)
    client.config = config
    return client
}