/*
 * pepipost_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for SortEnum enum
 */
type SortEnum int

/**
 * Value collection for SortEnum enum
 */
const (
    Sort_ASC SortEnum = 1 + iota
    Sort_DESC
)

func (r SortEnum) MarshalJSON() ([]byte, error) { 
    s := SortEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *SortEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  SortEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts SortEnum to its string representation
 */
func SortEnumToValue(sortEnum SortEnum) string {
    switch sortEnum {
        case Sort_ASC:
    		return "asc"		
        case Sort_DESC:
    		return "desc"		
        default:
        	return "asc"
    }
}

/**
 * Converts SortEnum Array to its string Array representation
*/
func SortEnumArrayToValue(sortEnum []SortEnum) []string {
    convArray := make([]string,len( sortEnum))
    for i:=0; i<len(sortEnum);i++ {
        convArray[i] = SortEnumToValue(sortEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func SortEnumFromValue(value string) SortEnum {
    switch value {
        case "ASC":
            return Sort_ASC
        case "DESC":
            return Sort_DESC
        default:
            return Sort_ASC
    }
}
